server:
  port: 8081

spring:
  config:
    import: optional:file:./etc/secrets/config.properties,optional:file:/etc/secrets/config.properties
  cache:
    type: redis
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL:localhost:9092}
    consumer:
      group-id: ordernest-inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      security:
        protocol: SSL
      ssl:
        truststore:
          type: PEM
          location: ${KAFKA_TRUSTSTORE_PATH:${user.dir}/src/main/resources/ca.pem}
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH:${user.dir}/src/main/resources/client.keystore.p12}
          password: changeit

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: 2s

app:
  kafka:
    topic:
      payment-events: payment.events
      order-cancelled-events: order.cancelled.events
    consumer:
      group-id: ordernest-inventory-service-payment-failed-consumer
      order-cancelled-group-id: ordernest-inventory-service-order-cancelled-consumer
  seed:
    enabled: true
