# Inventory service secrets (local / render secret file)

# Database
DB_URL=jdbc:postgresql://ep-fragrant-unit-ailk0gqi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
DB_USERNAME=neondb_owner
DB_PASSWORD=npg_vgtaq37FPiRZ

# Redis
REDIS_HOST=redis-17068.c267.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT=17068
REDIS_USERNAME=default
REDIS_PASSWORD=RFR23wWoK8pijGGTiliUYWNHdOYqt2cE

# Kafka
KAFKA_SERVICE_URL=kafka-877fe57-ordernest.i.aivencloud.com:14046

#KAFKA_TRUSTSTORE_PATH=/app/ssl/ca.pem
#KAFKA_KEYSTORE_PATH=/app/ssl/client.keystore.p12

KAFKA_TRUSTSTORE_PATH=${user.dir}/src/main/resources/ca.pem
KAFKA_KEYSTORE_PATH=${user.dir}/src/main/resources/client.keystore.p12
